### ISSUE TITLE
[Bug]: Load with inkscape conversion crashes

### ISSUE THREAD

**Issue by Nemes823** [meerk40t/meerk40t#1802]
### Summary Description

SVG file not load

### Additional Details

![PR0150](https://user-images.githubusercontent.com/130857191/232238095-2bcfaf44-7f59-440a-bd81-9e90cf055a4f.svg)

### Crash logs

```shell
MeerK40t crash log. Version: 0.8.2003 on Windows: Python 3.7.9: AMD64 - wxPython: 4.1.1 msw (phoenix) wxWidgets 3.1.5
Traceback (most recent call last):
  File "meerk40t\gui\wxmribbon.py", line 397, in button_click
  File "meerk40t\gui\wxmribbon.py", line 440, in _button_click_id
  File "meerk40t\gui\wxmmain.py", line 663, in <lambda>
  File "meerk40t\kernel\kernel.py", line 2151, in console
  File "meerk40t\kernel\kernel.py", line 2206, in _console_parse
  File "meerk40t\kernel\functions.py", line 279, in inner
  File "meerk40t\gui\wxmmain.py", line 1509, in load_dialog
  File "meerk40t\gui\wxmmain.py", line 3508, in clear_and_open
  File "meerk40t\gui\wxmmain.py", line 3529, in load
  File "meerk40t\core\elements.py", line 2984, in load
  File "meerk40t\extra\inkscape.py", line 528, in check_for_features
  File "meerk40t\extra\inkscape.py", line 73, in run_command_and_log
  File "subprocess.py", line 488, in run
  File "subprocess.py", line 800, in __init__
  File "subprocess.py", line 1148, in _execute_child
  File "subprocess.py", line 555, in list2cmdline
TypeError: argument of type 'int' is not iterable
```

### MeerK40t Version

MeerK40t v0.8.2003

### MeerK40t Type

Executable

### Your Operating System

Windows

**Comment by jpirnay** [comment]
That has been  fixed in the latest release
