### ISSUE TITLE
[Bug]: MAC OS 13.7.1 (22H221) INTEL - 0.9.5000 - CRASH

### ISSUE THREAD

**Issue by skasilov** [meerk40t/meerk40t#2693]
### Summary Description

Hi! 
[Bug]: MAC OS 13.7.1 (22H221) INTEL - 0.9.5000 - CRASH
This LOG 

### Crash logs

```shell
MeerK40t crash log. Version: 0.9.5000 on Darwin: Python 3.8.7: x86_64 - wxPython: 4.2.1 osx-cocoa (phoenix) wxWidgets 3.2.2.1
Traceback (most recent call last):
  File "mk40t.py", line 11, in <module>
  File "meerk40t/main.py", line 198, in run
  File "meerk40t/main.py", line 230, in _exe
  File "meerk40t/kernel/kernel.py", line 1150, in __call__
  File "meerk40t/kernel/kernel.py", line 860, in set_kernel_lifecycle
  File "meerk40t/gui/plugin.py", line 411, in plugin
  File "meerk40t/kernel/kernel.py", line 2296, in console
  File "meerk40t/kernel/kernel.py", line 2342, in _console_parse
  File "meerk40t/kernel/functions.py", line 286, in inner
  File "meerk40t/gui/wxmeerk40t.py", line 708, in window_open
  File "meerk40t/gui/wxmeerk40t.py", line 697, in window_open
  File "meerk40t/kernel/context.py", line 419, in open_as
  File "meerk40t/gui/wxmmain.py", line 243, in __init__
  File "meerk40t/gui/mwindow.py", line 36, in __init__
  File "meerk40t/gui/themes.py", line 150, in set_window_colors
wx._core.wxAssertionError: C++ assertion ""IsOk()"" failed at /private/var/folders/ng/qbrmmqsx6990j5cfzz6t_z0h0000gn/T/pip-install-x53_dp_9/wxpython_8de19be4eb1141a98a5a5d6b51ee1eb4/ext/wxWidgets/src/osx/core/colour.cpp(219) in OSXGetNSColor(): invalid colour


Local variables:
[mk40t.py:11, in <module>]:
__name__ : __main__
__doc__ : None
__package__ : None
__loader__ : <class '_frozen_importlib.BuiltinImporter'>
__spec__ : None
__annotations__ : {}
__builtins__ : <module 'builtins' (built-in)>
__file__ : /Users/kasilov/Desktop/MeerK40t.app/Contents/MacOS/mk40t.py
sys : <module 'sys' (built-in)>
pyimod03_importers : <module 'pyimod03_importers' from 'PyInstaller/loader/pyimod03_importers.py'>
os : <module 'os' from '/Users/kasilov/Desktop/MeerK40t.app/Contents/MacOS/os.pyc'>
VIRTENV : VIRTUAL_ENV
python_path : ['/Users/kasilov/Desktop/MeerK40t.app/Contents/MacOS/base_library.zip', '/Users/kasilov/Desktop/MeerK40t.app/Contents/MacOS/lib-dynload', '/Users/kasilov/Desktop/MeerK40t.app/Contents/MacOS']
pth : /Users/kasilov/Desktop/MeerK40t.app/Contents/MacOS
NullWriter : <class '__main__.NullWriter'>
encodings : <module 'encodings' from '/Users/kasilov/Desktop/MeerK40t.app/Contents/MacOS/base_library.zip/encodings/__init__.pyc'>
ctypes : <module 'ctypes' from '/Users/kasilov/Desktop/MeerK40t.app/Contents/MacOS/ctypes/__init__.pyc'>
LibraryLoader : <class 'ctypes.LibraryLoader'>
DEFAULT_MODE : 4
_frozen_name : <function _frozen_name at 0x7fd56850ab80>
PyInstallerImportError : <class '__main__.PyInstallerImportError'>
PyInstallerCDLL : <class '__main__.PyInstallerCDLL'>
PyInstallerPyDLL : <class '__main__.PyInstallerPyDLL'>
dyld : <module 'ctypes.macholib.dyld' from '/Users/kasilov/Desktop/MeerK40t.app/Contents/MacOS/ctypes/macholib/dyld.pyc'>
d : /Users/kasilov/Desktop/MeerK40t.app/Contents/MacOS/eggs
re : <module 're' from '/Users/kasilov/Desktop/MeerK40t.app/Contents/MacOS/base_library.zip/re.pyc'>
multiprocessing : <module 'multiprocessing' from '/Users/kasilov/Desktop/MeerK40t.app/Contents/MacOS/multiprocessing/__init__.pyc'>
spawn : <module 'multiprocessing.spawn' from '/Users/kasilov/Desktop/MeerK40t.app/Contents/MacOS/multiprocessing/spawn.pyc'>
_args_from_interpreter_flags : <function _args_from_interpreter_flags at 0x7fd56905d790>
_freeze_support : <function _freeze_support at 0x7fd568571ee0>
forking : <module 'multiprocessing.popen_fork' from '/Users/kasilov/Desktop/MeerK40t.app/Contents/MacOS/multiprocessing/popen_fork.pyc'>
spawning : <module 'multiprocessing.popen_spawn_posix' from '/Users/kasilov/Desktop/MeerK40t.app/Contents/MacOS/multiprocessing/popen_spawn_posix.pyc'>
FrozenSupportMixIn : <class '__main__.FrozenSupportMixIn'>
_Popen : <class '__main__._Popen'>
_Spawning_Popen : <class '__main__._Spawning_Popen'>
tcldir : /Users/kasilov/Desktop/MeerK40t.app/Contents/MacOS/tcl
tkdir : /Users/kasilov/Desktop/MeerK40t.app/Contents/MacOS/tk
is_darwin : True
pathlib : <module 'pathlib' from '/Users/kasilov/Desktop/MeerK40t.app/Contents/MacOS/pathlib.pyc'>
pkg_resources : <module 'pkg_resources' from '/Users/kasilov/Desktop/MeerK40t.app/Contents/MacOS/pkg_resources/__init__.pyc'>
FrozenImporter : <class 'pyimod03_importers.FrozenImporter'>
SYS_PREFIX : /Users/kasilov/Desktop/MeerK40t.app/Contents/MacOS
_TocFilesystem : <class '__main__._TocFilesystem'>
_toc_tree_cache : {}
PyiFrozenProvider : <class '__main__.PyiFrozenProvider'>
atexit : <module 'atexit' (built-in)>
shutil : <module 'shutil' from '/Users/kasilov/Desktop/MeerK40t.app/Contents/MacOS/shutil.pyc'>
tempfile : <module 'tempfile' from '/Users/kasilov/Desktop/MeerK40t.app/Contents/MacOS/tempfile.pyc'>
configdir : /var/folders/f1/7r77r6cj66582r_psqy1znp00000gn/T/org.tatarize.meerk40t/tmppkq80419
ssl : <module 'ssl' from '/Users/kasilov/Desktop/MeerK40t.app/Contents/MacOS/ssl.pyc'>
glob : <module 'glob' from '/Users/kasilov/Desktop/MeerK40t.app/Contents/MacOS/glob.pyc'>
libusb10 : <module 'usb.backend.libusb1' from '/Users/kasilov/Desktop/MeerK40t.app/Contents/MacOS/usb/backend/libusb1.pyc'>
libusb01 : <module 'usb.backend.libusb0' from '/Users/kasilov/Desktop/MeerK40t.app/Contents/MacOS/usb/backend/libusb0.pyc'>
openusb : <module 'usb.backend.openusb' from '/Users/kasilov/Desktop/MeerK40t.app/Contents/MacOS/usb/backend/openusb.pyc'>
get_load_func : <function get_load_func at 0x7fd5694aa3a0>
main : <module 'meerk40t.main' from '/Users/kasilov/Desktop/MeerK40t.app/Contents/MacOS/meerk40t/main.pyc'>
[meerk40t/main.py:198, in run]:
argv : []
args : Namespace(auto=False, batch=None, console=False, disable_ansi=False, execute=None, gui_suppress=False, input=None, language=None, lock_device_config=False, lock_general_config=False, maximized=False, minimized=False, no_gui=False, no_plugins=False, nuke_settings=False, output=None, profile=None, profiler=None, quit=False, set=None, simpleui=False, verbose=False, version=False)
python_version_required : (3, 6)
[meerk40t/main.py:230, in _exe]:
restarted : False
args : Namespace(auto=False, batch=None, console=False, disable_ansi=False, execute=None, gui_suppress=False, input=None, language=None, lock_device_config=False, lock_general_config=False, maximized=False, minimized=False, no_gui=False, no_plugins=False, nuke_settings=False, output=None, profile=None, profiler=None, quit=False, set=None, simpleui=False, verbose=False, version=False)
external_plugins : <function plugin at 0x7fd5695bb8b0>
internal_plugins : <function plugin at 0x7fd5695bba60>
Kernel : <class 'meerk40t.kernel.kernel.Kernel'>
kernel : Kernel(MeerK40t, MeerK40t, 0.9.5000)
auto : False
console : False
idx : 1
attrib : mktabpositions
[meerk40t/kernel/kernel.py:1150, in __call__]:
self : Kernel(MeerK40t, MeerK40t, 0.9.5000)
partial : False
[meerk40t/kernel/kernel.py:860, in set_kernel_lifecycle]:
self : Kernel(MeerK40t, MeerK40t, 0.9.5000)
kernel : Kernel(MeerK40t, MeerK40t, 0.9.5000)
position : 1000
args : ()
kwargs : {}
channel : Channel('kernel-lifecycle', buffer_size=0, line_end=None)
objects : [<meerk40t.kernel.kernel.Kernel object at 0x7fd5694fcb50>]
klp : <function Kernel.kernel_lifecycle_position at 0x7fd56963a8b0>
start : 0
end : 1000
k : Kernel(MeerK40t, MeerK40t, 0.9.5000)
plugin : <function plugin at 0x7fd56c566ca0>
plugin_list : [<function module_plugin at 0x7fd56c71b040>]
i : 0
domain : provider/device/ruida
module_path : module/wxMeerK40t
[meerk40t/gui/plugin.py:411, in plugin]:
lifecycle : mainloop
kernel_root : Context('/')
prompt_popup : <function plugin.<locals>.prompt_popup at 0x7fd571882820>
yesno_popup : <function plugin.<locals>.yesno_popup at 0x7fd571882af0>
BusyInfo : <class 'meerk40t.gui.busy.BusyInfo'>
kargs : {}
notification_message : <function plugin.<locals>.notification_message at 0x7fd571888670>
interrupt : <function plugin.<locals>.interrupt at 0x7fd5718888b0>
flag : False
icons : <module 'meerk40t.gui.icons' from '/Users/kasilov/Desktop/MeerK40t.app/Contents/MacOS/meerk40t/gui/icons.pyc'>
image : <wx._core.Bitmap object at 0x7fd5718880d0>
APPLICATION_VERSION : 0.9.5000
system : <function system at 0x7fd569147940>
shutdown : <function plugin.<locals>.shutdown at 0x7fd571888dc0>
_ : <built-in function GetTranslation>
kernel : Kernel(MeerK40t, MeerK40t, 0.9.5000)
meerk40tgui : wxMeerK40t(Context('/'), name="module/wxMeerK40t")
[meerk40t/kernel/kernel.py:2296, in console]:
self : Kernel(MeerK40t, MeerK40t, 0.9.5000)
data : window open MeerK40t
       
data_out : None
pos : 20
command : window open MeerK40t
[meerk40t/kernel/kernel.py:2342, in _console_parse]:
self : Kernel(MeerK40t, MeerK40t, 0.9.5000)
text : open MeerK40t
channel : Channel('console', buffer_size=0, line_end=None)
data : Context('/')
input_type : window
post : []
post_data : {}
_ : <built-in function GetTranslation>
pos : 4
remainder : MeerK40t
command : open
command_executed : False
funct : <function wxMeerK40t.sub_register.<locals>.window_open at 0x7fd56d5f20d0>
name : command/window/open
regex : open
match : re.compile('plan')
[meerk40t/kernel/functions.py:286, in inner]:
command : open
remainder : 
channel : Channel('console', buffer_size=0, line_end=None)
ik : {'_': <built-in function GetTranslation>, 'data': Context('/'), 'data_type': 'window', 'post': [], 'post_data': {}}
options : [{'type': <class 'int'>, 'help': 'Multi window flag for launching multiple copies of this window.', 'name': 'multi', 'short': 'm'}]
arguments : [{'type': <class 'str'>, 'help': 'window to be opened', 'name': 'window'}]
stack : [{'type': <class 'str'>, 'help': 'window to be opened', 'name': 'window'}]
kwargs : {'window': 'MeerK40t'}
argument_index : 1
opt_index : 1
pos : 8
nargs : 1
kind : PARAM
value : MeerK40t
start : 0
k : {'type': <class 'str'>, 'help': 'window to be opened', 'name': 'window'}
key : window
pk : {'type': <class 'int'>, 'help': 'Multi window flag for launching multiple copies of this window.', 'name': 'multi', 'short': 'm'}
current : ['MeerK40t']
command_return_context : None
func : <function wxMeerK40t.sub_register.<locals>.window_open at 0x7fd56d5f2040>
inner : <function wxMeerK40t.sub_register.<locals>.window_open at 0x7fd56d5f20d0>
[meerk40t/gui/wxmeerk40t.py:708, in window_open]:
command : open
data : Context('/')
multi : None
kwargs : {'data_type': 'window', 'post': [], 'post_data': {}}
context : Context('/')
window_class : <class 'meerk40t.gui.wxmmain.MeerK40t'>
new_path : None
window_open : <function wxMeerK40t.sub_register.<locals>.window_open.<locals>.window_open at 0x7fd571888ca0>
window_close : <function wxMeerK40t.sub_register.<locals>.window_open.<locals>.window_close at 0x7fd571888a60>
_ : <built-in function GetTranslation>
args : ()
channel : Channel('console', buffer_size=0, line_end=None)
parent : None
path : Context('/')
window : MeerK40t
window_name : window/MeerK40t
window_uri : window/MeerK40t
kernel : Kernel(MeerK40t, MeerK40t, 0.9.5000)
[meerk40t/gui/wxmeerk40t.py:697, in window_open]:
a : (None,)
k : {}
_ : <built-in function GetTranslation>
args : ()
channel : Channel('console', buffer_size=0, line_end=None)
parent : None
path : Context('/')
window : MeerK40t
window_name : window/MeerK40t
window_uri : window/MeerK40t
[meerk40t/kernel/context.py:419, in open_as]:
self : Context('/')
registered_path : window/MeerK40t
instance_path : window/MeerK40t
args : (None,)
kwargs : {}
open_object : <class 'meerk40t.gui.wxmmain.MeerK40t'>
[meerk40t/gui/wxmmain.py:243, in __init__]:
self : MeerK40t(Context('/'), name="window/MeerK40t")
args : (Context('/'), 'window/MeerK40t', None)
kwds : {}
width : 1920
height : 1080
__class__ : <class 'meerk40t.gui.wxmmain.MeerK40t'>
[meerk40t/gui/mwindow.py:36, in __init__]:
self : MeerK40t(Context('/'), name="window/MeerK40t")
width : 1728
height : 972
context : Context('/')
path : window/MeerK40t
parent : None
style : 541072960
args : ()
kwds : {}
[meerk40t/gui/themes.py:150, in set_window_colors]:
self : Service('themes', None)
win : MeerK40t(Context('/'), name="window/MeerK40t")
tp : {'win_bg': None, 'win_fg': None, 'button_bg': None, 'button_fg': None, 'text_bg': None, 'text_fg': None, 'list_bg': None, 'list_fg': None, 'label_bg': None, 'label_fg': None, 'highlight': None, 'inactive_bg': None, 'inactive_fg': None, 'pause_bg': None, 'pause_fg': wx.Colour(0, 0, 0, 216), 'start_bg': None, 'start_fg': None, 'start_bg_inactive': None, 'start_fg_focus': None, 'stop_bg_inactive': None, 'stop_bg': None, 'stop_fg': None, 'stop_fg_focus': None, 'arm_bg': None, 'arm_fg': None, 'arm_bg_inactive': None, 'arm_fg_focus': None}
```

### MeerK40t Version

0.9.5000

### MeerK40t Type

Git

### Your Operating System

Mac (before M1/Bigsur)

**Comment by jpirnay** [comment]
This is on startup? Can you please provide a bit more context - thank you

**Comment by skasilov** [comment]
Good afternoon! 
Thank you so much for your response and willingness to help! 
I'm sorry - I just thought it was clear from this log. 
When the application starts, this error is displayed with a suggestion to send a report to the developers! 
When choosing ANY answer YES or NO, the application freezes dead! 
Only forcibly closing the application helps! 
Previous versions work fine! 
I really hope that you will solve the problem!


Sincerely Sergey Kasilov
CEO/CTO
+31617349421

The Netherlands
Catharina van Rennesstraat 8,
2511AT, 's-Gravenhage
https://www.linkedin.com/in/sergey-kasilov
https://www.innerquill.com
https://www.etsy.com/shop/InnerQuill
https://www.instagram.com/innerquill.project

Unique tools for creativity and calligraphy.
3D printing - 3D scanning - Laser Engraving Personalization.

￼

**Comment by jpirnay** [comment]
I assumed so, but I am always happy to receive as much context as possible.
Are you able to run from source? Rhen I would like to see whether the issue is still in place with the latest github code.

**Comment by skasilov** [comment]
Thanks for the answer! 
No! 
As usual, I downloaded the INTEL Mac version - I moved it to the "programs" folder
and even tried to transfer it to another disk! 
The result is the same - an error when starting and freezing the program!


Sincerely Sergey Kasilov
CEO/CTO
+31617349421

The Netherlands
Catharina van Rennesstraat 8,
2511AT, 's-Gravenhage
https://www.linkedin.com/in/sergey-kasilov
https://www.innerquill.com
https://www.etsy.com/shop/InnerQuill
https://www.instagram.com/innerquill.project

Unique tools for creativity and calligraphy.
3D printing - 3D scanning - Laser Engraving Personalization.

￼

**Comment by jpirnay** [comment]
I would be grateful for your meerk40t.cfg file, to be able to check what's going on.
(You could try to move that file to a different location to force mk to start from scratch, not using any stored settings, does the crash then still happen?)
Are you running on proper Apple Hardware or on a hackintosh style system?

**Comment by skasilov** [comment]
Hi! 
Thank you so much for your help! 
Can you help me - where to look for this meerk40t.cfg file? 
The search doesn't show anything!! 
I have an original Mac mini


Sincerely Sergey Kasilov
CEO/CTO
+31617349421

The Netherlands
Catharina van Rennesstraat 8,
2511AT, 's-Gravenhage
https://www.linkedin.com/in/sergey-kasilov
https://www.innerquill.com
https://www.etsy.com/shop/InnerQuill
https://www.instagram.com/innerquill.project

Unique tools for creativity and calligraphy.
3D printing - 3D scanning - Laser Engraving Personalization.


￼

**Comment by skasilov** [comment]
This is very strange! 
I don't even have this folder there :-)))


Sincerely Sergey Kasilov
CEO/CTO
+31617349421

The Netherlands
Catharina van Rennesstraat 8,
2511AT, 's-Gravenhage
https://www.linkedin.com/in/sergey-kasilov
https://www.innerquill.com
https://www.etsy.com/shop/InnerQuill
https://www.instagram.com/innerquill.project

Unique tools for creativity and calligraphy.
3D printing - 3D scanning - Laser Engraving Personalization.

￼


￼

**Comment by jpirnay** [comment]
I think I have covered it, so you need to wait for the compile of the new release.

**Comment by skasilov** [comment]
> I think I have covered it, so you need to wait for the compile of the new release.

Perfect! Will be waiting with hope!

**Comment by skasilov** [comment]
Problem solved with last version! Your are the BEST! Thank you!

**Comment by jpirnay** [comment]
Great, good to hear
