### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by inspectionsbybob** [meerk40t/meerk40t#363]
MeerK40t crash log. Version: 0.6.16
Please report to: https://github.com/meerk40t/meerk40t/issues

Traceback (most recent call last):
  File "Kernel.py", line 1725, in run
  File "Kernel.py", line 1923, in run
  File "Kernel.py", line 1790, in shutdown
  File "Kernel.py", line 2182, in close
  File "Kernel.py", line 100, in detach
  File "Navigation.py", line 371, in finalize
RuntimeError: wrapped C/C++ object of type SpinCtrlDouble has been deleted

**Comment by tatarize** [comment]
Um. That's version 6.16. Seems like you might want to upgrade. I think that bit of code got changed accordingly.

We're at 0.6.19 for regular releases and 0.6.20 pretty deep in the betas.

**Comment by inspectionsbybob** [comment]
Closed fixed
