### ISSUE TITLE
Camera Close, Redraw Crash

### ISSUE THREAD

**Issue by inspectionsbybob** [meerk40t/meerk40t#366]
MeerK40t crash log. Version: 0.6.19
Please report to: https://github.com/meerk40t/meerk40t/issues

Traceback (most recent call last):
  File "CameraInteface.py", line 236, in on_size
  File "CameraInteface.py", line 648, in update_in_gui_thread
  File "CameraInteface.py", line 460, in on_update_buffer
AttributeError: 'NoneType' object has no attribute 'draw_mode'

**Comment by tatarize** [comment]
Hm.  Tried to draw after window shutdown. I'll look into that.

**Comment by tatarize** [comment]
https://github.com/meerk40t/meerk40t/releases/tag/0.6.20-beta7

This is fixed in the Beta7.

**Comment by tatarize** [comment]
This is fixed in 0.6.20.
