### ISSUE TITLE
error report (6.19)

### ISSUE THREAD

**Issue by inspectionsbybob** [meerk40t/meerk40t#368]
Not sure if this is a duplicate

MeerK40t crash log. Version: 0.6.19
Please report to: https://github.com/meerk40t/meerk40t/issues

Traceback (most recent call last):
  File "CameraInteface.py", line 236, in on_size
  File "CameraInteface.py", line 648, in update_in_gui_thread
  File "CameraInteface.py", line 460, in on_update_buffer
AttributeError: 'NoneType' object has no attribute 'draw_mode'

**Comment by tatarize** [comment]
#366 is same. But, it's fine. It's a relevant and open bug. I'd prefer 2 reports to 0.

**Comment by inspectionsbybob** [comment]
Go ahead a close it as a duplicate.

Bob S.
