### ISSUE TITLE
TypeError exception while importing SVG

### ISSUE THREAD

**Issue by dietervansteenwegen** [meerk40t/meerk40t#44]
Traceback:
Traceback (most recent call last):
File "MeerK40t.py", line 417, in on_click_import
File "MeerK40t.py", line 332, in load_svg
File "LaserProject.py", line 371, in svg_transform
File "svg_parser.py", line 377, in parse_svg_transform
TypeError: post_cat() takes 2 positional arguments but 7 were given

**Comment by tatarize** [comment]
Should be fixed by https://github.com/meerk40t/meerk40t/commit/aa2f4997e148a0879234cc61e899c2e7c13130aa which should be included int 0.1.3 and in the release package. But this does imply I should find a good set of test SVGs and try them to make sure things at least work.
