### ISSUE TITLE
Error spooling PNG images

### ISSUE THREAD

**Issue by Cyber-phobia** [meerk40t/meerk40t#56]
8-bit Grayscale PNG images are not spooling to engrave.
I tested this with 24-bit colour images and they were able to spool and engrave.

Tried multiple times with an 8-bit grayscale image and received the following error message;
Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "LhymicroWriter.py", line 94, in run
  File "LaserProject.py", line 329, in generate
  File "RasterPlotter.py", line 183, in plot_raster
  File "RasterPlotter.py", line 21, in leftmost_not_equal
  File "LaserProject.py", line 296, in filter
TypeError: 'int' object is not subscriptable

**Comment by tatarize** [comment]
Yeah, without a 3 x 8 byte color model, or 4 x 8 it gets rather than a tuple of bytes a single int which then it tries to address like color[0] which it can't because it's an int. Good catch. Lemme try some other color models and add in fallbacks.

**Comment by tatarize** [comment]
Okay #59 will fix this, I'll have check for interference with some other work I'm doing before pushing it through.

**Comment by tatarize** [comment]
This is now live in 0.1.5
