### ISSUE TITLE
Linux Settings, tree too small crash

### ISSUE THREAD

**Issue by tatarize** [meerk40t/meerk40t#648]
In Linux if you make the tree too small when you try to reload it will crash with a BadItem crash. See CrashLogs:
https://github.com/meerk40t/meerk40t/projects/6

```
MeerK40t crash log. Version: 0.7.2 on linux - 4.1.1 gtk3 (phoenix) wxWidgets 3.1.5
Traceback (most recent call last):
  File "wx/core.py", line 3407, in <lambda>
  File "meerk40t/kernel.py", line 1705, in process_queue
  File "meerk40t/gui/wxmeerk40t.py", line 2327, in on_rebuild_tree_signal
  File "meerk40t/gui/wxmeerk40t.py", line 3482, in rebuild_tree
ValueError: Bad Item
```

**Comment by tatarize** [comment]
https://github.com/meerk40t/meerk40t/commit/d636f53fb37821d9773d9b2ada661ccd7055dc85

Found and fixed.

**Comment by tatarize** [comment]
Corrected.
