### ISSUE TITLE
[Crash] SetAttr error in svgio.py when loading previous save

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#724]
```
MeerK40t crash log. Version: 0.7.5-beta1 git on Windows:AMD64 - 4.1.1 msw (phoenix) wxWidgets 3.1.5
Traceback (most recent call last):
  File "D:\MeerK40t-64\Source\meerk40t_meerk40t\meerk40t\gui\wxmmain.py", line 1663, in <lambda>
    lambda e: self.load_or_open(context.file0),
  File "D:\MeerK40t-64\Source\meerk40t_meerk40t\meerk40t\gui\wxmmain.py", line 1624, in load_or_open
    self.load(filename)
  File "D:\MeerK40t-64\Source\meerk40t_meerk40t\meerk40t\gui\wxmmain.py", line 1762, in load
    results = self.context.load(
  File "D:\MeerK40t-64\Source\meerk40t_meerk40t\meerk40t\core\elements.py", line 6575, in load
    results = loader.load(self.context, self, pathname, **kwargs)
  File "D:\MeerK40t-64\Source\meerk40t_meerk40t\meerk40t\core\svg_io.py", line 292, in load
    result = SVGLoader.parse(
  File "D:\MeerK40t-64\Source\meerk40t_meerk40t\meerk40t\core\svg_io.py", line 410, in parse
    setattr(
AttributeError: can't set attribute
```

**Comment by Sophist-UK** [comment]
Original Inkscape file loads fine. Use rasterwizard and set op speeds etc and save. When you try to reload you get this...

Running source from `main` branch. Do not get this crash on 7.5.1 beta 1 executable.

[Key rings - N2 Museum.zip](https://github.com/meerk40t/meerk40t/files/7798321/Key.rings.-.N2.Museum.zip)
