### ISSUE TITLE
Moshi Device crash with Connection Error

### ISSUE THREAD

**Issue by tatarize** [meerk40t/meerk40t#737]
```
MeerK40t crash log. Version: 0.7.5-beta1 on win32 - 4.1.1 msw (phoenix) wxWidgets 3.1.5

Traceback (most recent call last):
  File "meerk40t\device\ch341\ch341libusbdriver.py", line 332, in CH341EppWrite
  File "usb\core.py", line 994, in write
...
  File "usb\backend\libusb0.py", line 447, in _check
usb.core.USBError: [Errno None] b'libusb0-dll:err [submit_async] submitting request failed, win error: Urz\xb9dzenie nie rozpoznaje polecenia.\r\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "meerk40t\gui\panes\laserpanel.py", line 294, in on_button_stop
  File "meerk40t\kernel.py", line 136, in __call__
...
  File "meerk40t\device\moshi\moshidevice.py", line 810, in realtime_pipe
  File "meerk40t\device\ch341\libusb.py", line 82, in write_addr
  File "meerk40t\device\ch341\ch341libusbdriver.py", line 411, in CH341EppWriteAddr
  File "meerk40t\device\ch341\ch341libusbdriver.py", line 338, in CH341EppWrite
ConnectionError
```
3x copies of this error submitted.

**Comment by tatarize** [comment]
Additionally for Moshi:

```
MeerK40t crash log. Version: 0.7.3 on win32 - 4.1.1 msw (phoenix) wxWidgets 3.1.5
Traceback (most recent call last):
  File "meerk40t\kernel.py", line 1492, in run
  File "meerk40t\core\drivers.py", line 124, in _driver_threaded
  File "meerk40t\core\drivers.py", line 149, in _process_spooled_item
  File "meerk40t\core\drivers.py", line 272, in command
  File "meerk40t\device\moshi\moshidevice.py", line 361, in ensure_rapid_mode
  File "meerk40t\device\moshi\moshiblob.py", line 431, in termination
AssertionError
```

**Comment by tatarize** [comment]
```python
MeerK40t crash log. Version: 0.7.7001 pkg on Windows:AMD64 - 4.2.0 msw (phoenix) wxWidgets 3.2.0
Traceback (most recent call last):
  File "C:\Users\Corte\AppData\Local\Programs\Python\Python310\lib\site-packages\meerk40t\kernel.py", line 1637, in run
    func_result = func(*args)
  File "C:\Users\Corte\AppData\Local\Programs\Python\Python310\lib\site-packages\meerk40t\core\drivers.py", line 122, in _driver_threaded
    self._process_spooled_item()
  File "C:\Users\Corte\AppData\Local\Programs\Python\Python310\lib\site-packages\meerk40t\core\drivers.py", line 147, in _process_spooled_item
    if not self.command(e):
  File "C:\Users\Corte\AppData\Local\Programs\Python\Python310\lib\site-packages\meerk40t\core\drivers.py", line 221, in command
    self.move(x, y)
  File "C:\Users\Corte\AppData\Local\Programs\Python\Python310\lib\site-packages\meerk40t\device\moshi\moshidevice.py", line 546, in move
    self.move_relative(x, y)
  File "C:\Users\Corte\AppData\Local\Programs\Python\Python310\lib\site-packages\meerk40t\device\moshi\moshidevice.py", line 571, in move_relative
    self.move_absolute(x, y)
  File "C:\Users\Corte\AppData\Local\Programs\Python\Python310\lib\site-packages\meerk40t\device\moshi\moshidevice.py", line 558, in move_absolute
    self.program.move_abs(x, y)
  File "C:\Users\Corte\AppData\Local\Programs\Python\Python310\lib\site-packages\meerk40t\device\moshi\moshiblob.py", line 468, in move_abs
    assert 2 <= self._stage <= 3
AssertionError
```
