### ISSUE TITLE
Common Crash, likely for memory error

### ISSUE THREAD

**Issue by tatarize** [meerk40t/meerk40t#738]
```
MeerK40t crash log. Version: 0.7.4 on win32 - 4.1.1 msw (phoenix) wxWidgets 3.1.5
Traceback (most recent call last):
  File "meerk40t\gui\wxmribbon.py", line 207, in open_simulator
  File "meerk40t\kernel.py", line 136, in __call__
  File "meerk40t\kernel.py", line 1842, in console
  File "meerk40t\kernel.py", line 1928, in _console_parse
  File "meerk40t\kernel.py", line 1277, in inner
  File "meerk40t\core\planner.py", line 1028, in plan_validate
  File "meerk40t\core\planner.py", line 286, in execute
  File "meerk40t\core\planner.py", line 581, in make_image
  File "meerk40t\core\planner.py", line 568, in make_image_for_op
  File "meerk40t\gui\laserrender.py", line 497, in make_raster
wx._core.wxAssertionError: C++ assertion "bmp.IsOk()" failed at ..\..\src\msw\graphics.cpp(2575) in wxGDIPlusRenderer::CreateContext(): Should select a bitmap before creating wxGCDC
```

We may want to torture the system memory and just quietly tell the user rather than crash out.

**Comment by tatarize** [comment]
This is generally done now in 0.8.x
